version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3001" 
    environment:
      - DOCKER_ENV=local  
      - MONGODB_URI=mongodb://mongodb:27017/project-splitdeal
      - PORT=3000  
      - JWT_SECRET=${JWT_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - splitdeal-network

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=project-splitdeal
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - splitdeal-network

volumes:
  mongodb_data:

networks:
  splitdeal-network:
    driver: bridge